Damage and repair robots
inf112-v21/IsolasjonsTeamet pull request #28
Opened 2021-03-05 14:30 UTC by espensva

2021-03-05 14:33 UTC, Katrix requested changes

2021-03-05 14:33 UTC, Katrix commented on src/test/java/inf112/isolasjonsteamet/roborally/PlayerSpec.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/test/java/inf112/isolasjonsteamet/roborally/PlayerSpec.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/test/java/inf112/isolasjonsteamet/roborally/PlayerSpec.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/test/java/inf112/isolasjonsteamet/roborally/PlayerSpec.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/test/java/inf112/isolasjonsteamet/roborally/PlayerSpec.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/test/java/inf112/isolasjonsteamet/roborally/PlayerSpec.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/test/java/inf112/isolasjonsteamet/roborally/PlayerSpec.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/test/java/inf112/isolasjonsteamet/roborally/PlayerSpec.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/test/java/inf112/isolasjonsteamet/roborally/PlayerSpec.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/test/java/inf112/isolasjonsteamet/roborally/PlayerSpec.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/test/java/inf112/isolasjonsteamet/roborally/PlayerSpec.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/app/Game.java
> +package inf112.isolasjonsteamet.roborally.app;
Let's delete this class. It was never intended to follow with the merge.

2021-03-05 14:33 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/Uturn.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/Uturn.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/RotateRight.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/RotateLeft.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/RotateLeft.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/RepairPlayer.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/PowerDown.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/KillRobot.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/Direction.java
> +package inf112.isolasjonsteamet.roborally.actions;
Let's delete this class too again

2021-03-05 14:33 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/Destruction.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/Damage.java
> +
Remove newline

2021-03-05 14:33 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/CheckPoint.java
> +
Remove newline

2021-03-07 23:23 UTC, Katrix requested changes
Fix these things, fix checkstyle, fix your tests, and implement Checkpoint too here, and this should be done.

2021-03-07 23:23 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/Damage.java
> +	/**
Use `{@inheritDoc}` here instead of copying the comment.

2021-03-07 23:23 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/KillRobot.java
> +	/**
Use `{@inheritDoc}` here instead of copying the comment.

2021-03-07 23:23 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/RepairPlayer.java
> +	/**
Use `{@inheritDoc}` here instead of copying the comment.

2021-03-07 23:23 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/players/Player.java
> +	 * If a player gets 10 damageTokens on his robot, player loose 1 life
This comment should more describe what the method does (decrements the life, and resets damage tokens)

2021-03-15 13:10 UTC, kme020 reviewed
Make sure all the checks passes

2021-03-18 13:37 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/KillRobot.java
> +	/**
Remove the existing comment here, and keep only `@inheritDoc`

2021-03-18 13:56 UTC, Katrix approved these changes

2021-03-19 09:35 UTC, kme020 approved these changes
Nice

2021-03-19 10:15 UTC, merged