Add smooth movement for player effects
inf112-v21/IsolasjonsTeamet pull request #62
Opened 2021-04-21 15:01 UTC by kme020

Player now moves smoothly around the board. Looks more clean. Rotation effect still needs to be added.

2021-04-21 15:22 UTC, Katrix requested changes

2021-04-21 15:22 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/ActionProcessor.java
> +	void scheduleAction(Player player, Action action);
Javadoc

2021-04-21 15:22 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/actions/Move.java
> +	/**
Add back `@Override` and use `{@inheritDoc}`

2021-04-21 15:22 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/app/RoboRallyGame.java
> +		var bottomConsole = new PrintStreamLabel(3, System.out, skin, "default-font", Color.WHITE);
Merge conflict gone wrong here. You have removed tons of work from master.

2021-04-21 15:22 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/app/RoboRallyGame.java
> +		@SuppressWarnings("VariableDeclarationUsageDistance")
If you need to ignore this warning, declare the field as final instead.

2021-04-21 15:22 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/board/ClientBoard.java
> +	void show(Player player);
Javadoc

2021-04-21 15:22 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/effects/PlayerEffect.java
> +	Orientation dir;
Make this private

2021-04-21 15:22 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/gui/MapRendererWidget.java
> -
Don't remove the newlines here. They're useful to indicate which batch is active where

2021-04-21 15:22 UTC, Katrix commented on src/test/java/inf112/isolasjonsteamet/roborally/PlayerSpec.java
> +	    action.initialize(board, player);
Formatting

2021-04-21 15:22 UTC, Katrix commented on src/test/java/inf112/isolasjonsteamet/roborally/PlayerSpec.java
> +import java.util.List;
Don't move the imports

2021-04-22 12:02 UTC, Katrix commented on src/main/java/inf112/isolasjonsteamet/roborally/gui/MapRendererWidget.java
> +	/**
`{@inheritDoc}` in here. Even more important for some of the other methods in here, as the JavaDoc specified here is just plain wrong in some cases.

2021-04-22 13:47 UTC, Katrix approved these changes

2021-04-22 13:53 UTC, espensva approved these changes

2021-04-22 13:54 UTC, merged